
	<fieldset>
		<legend>Information Utilisateur</legend>
		<form action="" method="Post">
			<ul>
				<li>
					<label for="firstName" name="firstName">Nom :</label>
					<input id="firstName" type="text" name="firstName">
				</li>
				<li>
					<label for="lastName" name="lastName">prenom :</label>
					<input id="lastName" type="text" name="lastName">
				</li>
				<li>
					<label for="nickName" name="nickName">pseudo :</label>
					<input id="nickName" type="text" name="nickName">
				</li>

				<li>
					<label for="mail" name="mail">E-mail :</label>
					<input id="mail" type="text" name="mail">
				</li>
				<li>
					<label for="password" name="password">Mot de passe :</label>
					<input id="password" type="text" name="password">
				</li>
				<li>
					<label for="statue" name="statue">Mot de passe :</label>
					<select id="statue" name="statue">
						<option value="vendeur">vendeur</option>
						<option value="client">client</option>
					</select>
				</li>

			</ul>
			<button type="submit" >s'enregistrer</button>
		</form>
	</fieldset>
	







