
<ul>
	<li><?= $_SESSION['firstName']?><?= $_SESSION['lastName']?></li>
	<li><?= $_SESSION['Adress']?></li>
	<li><?= $_SESSION['PostalCode']?><?= $_SESSION['City']?></li>
	</li>
</ul>
<div id="recap"> 

</div>


<p>commandé le </p>
<form action="<?= $requestUrl ?>/payment" method="POST">
<h2>Merci de bien vouloir procéder au paiement de la commande</h2>
<input id="confirm" type="hidden" name="orderTotal" value=""/>
<button type="submit">payer</button>
<button >annuler</button>

</form>
 <div class="container">
      <h2 class="my-4 text-center">Intro to react course price 50$</h2>
      <form action="<?= $requestUrl ?>/payment" method="post" id="payment-form">
        <div class="form-row">
          <input type="text" class="form-control mb-3 StripeElement StripeElemen--empty" placeHolder="Prénom" name="first_name">

          <input type="text" class="form-control mb-3 StripeElement StripeElemen--empty" placeHolder="Nom" name="last_name">

          <input type="email" class="form-control mb-3 StripeElement StripeElemen--empty" placeHolder="Email" name="email">

          <div id="card-element" class="form-control ">
            <!-- A Stripe Element will be inserted here. -->
          </div>

          <!-- Used to display form errors. -->
          <div id="card-errors" role="alert"></div>
        </div>

        <button>Submit Payment</button>
      </form>
    </div>
    <script src="https://js.stripe.com/v3/"></script>
    <script src="<?= $wwwUrl ?>/js/charge.js"></script>







<script type="text/javascript" src="<?= $wwwUrl ?>/js/classes/Panier.class.js"></script>
<script type="text/javascript" src="<?= $wwwUrl ?>/js/classes/MealAjax.class.js"></script>
<script type="text/javascript" src="<?= $wwwUrl ?>/js/classes/Payment.class.js"></script>