<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Loterie 3Wacademy</title>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans">
    <link rel="stylesheet" href="lottery.css">
</head>
<body>
    <header>
        <h1>Traducteur Anglais - Français</h1>
    </header>
    <form>
        <label for="mot">mot : </label>
        <input id="mot" type="text" value="">
      
    </form>
    
    <form action="" >
      
        <label for="sens">mot : </label>
        <select name="panier">
            <option value="fraises">Fraises</option>
            <option value="bananes">Bananes</option>
            <option value="carottes" selected>Carottes</option>
            <option value="navets">Navets</option>
        </select>
    </form>
</body>
</html>