<!-- Message de notification -->

<!-- Code HTML à écrire -->


<!-- Liste des aliments -->
<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>
    <tbody>
        <!-- Code HTML à écrire -->
       
			
      		
	        <?php foreach($meals as $meal) :?>

		        <tr>
		        	<td>
		        		<img src="<?= $wwwUrl ?>/images/meals/<?=$meal['Photo']?>"/>
		        	</td>
		        	<td>
		       		 	<p><?=$meal['Name']?></p>
		        		<p><?=$meal['Description']?></p>
		        	</td>
		        	<td>
		        		<p><?=$meal['SalePrice']?></p>
		        	</td>
		       

		         </tr>
		    <?php endforeach  ?>
		   

    </tbody>
</table>