<!DOCTYPE html>
	<html lang="en">
	<head>
		<meta charset="UTF-8">
		 <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>
		 <link rel="stylesheet" href="index.css">
		<title>Document</title>
	</head>
	<body>

a. <ul><p>Lorem ipsum dolor sit amet</p></ul>
b. <p><a href="#"><img src="images/logo.png" alt="Logo de la société"></a></p>
c. <article>Lorem ipsum dolor sit amet</artcle>
d. <p><a href="#">c'est un lien</p></a>

		 <script src="index.js"></script>
	</body>
</html>