<form action="<?= $requestUrl ?>/user/login" method="POST">
	<fieldset>
			<legend>Informations d'authentification </legend>
			<li>
					<label for="mail" name="mail">mail:</label>
					<input id="mail" type="mail" name="mail">

				</li>
				<li>
					<label for="psw" name="psw">mot de pass :</label>
					<input id="psw" type="password" name="psw">

				</li>

		</fieldset>





	<button type="submit">Connexion</button>

</form>
