<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM5hqvlk\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM5hqvlk/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerM5hqvlk.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerM5hqvlk\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerM5hqvlk\srcApp_KernelProdContainer([
    'container.build_hash' => 'M5hqvlk',
    'container.build_id' => 'c78bbd15',
    'container.build_time' => 1559135739,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM5hqvlk');
