<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Ga9BzVC' shared service.

return $this->privates['.service_locator.Ga9BzVC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'option' => ['privates', '.errored..service_locator.Ga9BzVC.App\\Entity\\Options', NULL, 'Cannot autowire service ".service_locator.Ga9BzVC": it references class "App\\Entity\\Options" but no such service exists.'],
]);
