<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.N38ovWA' shared service.

return $this->privates['.service_locator.N38ovWA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'property' => ['privates', '.errored..service_locator.N38ovWA.App\\Entity\\Property', NULL, 'Cannot autowire service ".service_locator.N38ovWA": it references class "App\\Entity\\Property" but no such service exists.'],
]);
