<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.Ga9BzVC.App\Entity\Options' shared service.

include_once $this->targetDirs[3].'\\src\\Entity\\Options.php';

return $this->privates['.errored..service_locator.Ga9BzVC.App\Entity\Options'] = new \App\Entity\Options();
