<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.qLdd_t1' shared service.

return $this->privates['.service_locator.qLdd_t1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'pictures' => ['privates', '.errored..service_locator.qLdd_t1.App\\Entity\\Pictures', NULL, 'Cannot autowire service ".service_locator.qLdd_t1": it references class "App\\Entity\\Pictures" but no such service exists.'],
]);
