<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\TraceableValueResolver.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\Admin\\AdminOptionsController::delete' => ['privates', '.service_locator.Ga9BzVC', 'get_ServiceLocator_Ga9BzVCService.php', true],
    'App\\Controller\\Admin\\AdminOptionsController::edit' => ['privates', '.service_locator.Ga9BzVC', 'get_ServiceLocator_Ga9BzVCService.php', true],
    'App\\Controller\\Admin\\AdminOptionsController::index' => ['privates', '.service_locator.0zcUV8a', 'get_ServiceLocator_0zcUV8aService.php', true],
    'App\\Controller\\Admin\\AdminOptionsController::show' => ['privates', '.service_locator.Ga9BzVC', 'get_ServiceLocator_Ga9BzVCService.php', true],
    'App\\Controller\\Admin\\AdminPropertyController::delete' => ['privates', '.service_locator.N38ovWA', 'get_ServiceLocator_N38ovWAService.php', true],
    'App\\Controller\\Admin\\AdminPropertyController::edit' => ['privates', '.service_locator.N38ovWA', 'get_ServiceLocator_N38ovWAService.php', true],
    'App\\Controller\\Admin\\AdminPropertyController::new' => ['privates', '.service_locator.qLdd_t1', 'get_ServiceLocator_QLddT1Service.php', true],
    'App\\Controller\\HomeController::index' => ['privates', '.service_locator.zf96HF0', 'get_ServiceLocator_Zf96HF0Service.php', true],
    'App\\Controller\\PropertyController::index' => ['privates', '.service_locator.jVNF2GQ', 'get_ServiceLocator_JVNF2GQService.php', true],
    'App\\Controller\\PropertyController::show' => ['privates', '.service_locator.N38ovWA', 'get_ServiceLocator_N38ovWAService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\Admin\\AdminOptionsController:delete' => ['privates', '.service_locator.Ga9BzVC', 'get_ServiceLocator_Ga9BzVCService.php', true],
    'App\\Controller\\Admin\\AdminOptionsController:edit' => ['privates', '.service_locator.Ga9BzVC', 'get_ServiceLocator_Ga9BzVCService.php', true],
    'App\\Controller\\Admin\\AdminOptionsController:index' => ['privates', '.service_locator.0zcUV8a', 'get_ServiceLocator_0zcUV8aService.php', true],
    'App\\Controller\\Admin\\AdminOptionsController:show' => ['privates', '.service_locator.Ga9BzVC', 'get_ServiceLocator_Ga9BzVCService.php', true],
    'App\\Controller\\Admin\\AdminPropertyController:delete' => ['privates', '.service_locator.N38ovWA', 'get_ServiceLocator_N38ovWAService.php', true],
    'App\\Controller\\Admin\\AdminPropertyController:edit' => ['privates', '.service_locator.N38ovWA', 'get_ServiceLocator_N38ovWAService.php', true],
    'App\\Controller\\Admin\\AdminPropertyController:new' => ['privates', '.service_locator.qLdd_t1', 'get_ServiceLocator_QLddT1Service.php', true],
    'App\\Controller\\HomeController:index' => ['privates', '.service_locator.zf96HF0', 'get_ServiceLocator_Zf96HF0Service.php', true],
    'App\\Controller\\PropertyController:index' => ['privates', '.service_locator.jVNF2GQ', 'get_ServiceLocator_JVNF2GQService.php', true],
    'App\\Controller\\PropertyController:show' => ['privates', '.service_locator.N38ovWA', 'get_ServiceLocator_N38ovWAService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
