<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.qLdd_t1.App\Entity\Pictures' shared service.

include_once $this->targetDirs[3].'\\src\\Entity\\Pictures.php';

return $this->privates['.errored..service_locator.qLdd_t1.App\Entity\Pictures'] = new \App\Entity\Pictures();
