<h2><i class="fa fa-pencil"></i> Rédiger un nouvel article</h2>

<!-- Formulaire de saisie d'un nouvel article -->
<form class="generic-form" action="add_Post.php" method="post">
    <fieldset>
        <legend><i class="fa fa-sticky-note-o"></i> Nouvel article</legend>
        <ul>
            <li>
                <label for="title">Titre :</label>
                <input type="text" id="title" name="title">
            </li>
            <li>
                <label class="textarea" for="contents">Article :</label>
                <textarea id="contents" name="contents" rows="15"></textarea>
            </li>
            <li>
                <label for="author">Auteur :</label>
                <select id="author" name="author">
                    <?php foreach ($Authors as $author) :?>
                    	<option value="<?= $author['Id']?> "><?= $author['FirstName'].' '.$author['LastName'] ?></option>

                    <?php endforeach ?>    
                 </select>
            </li>
            <li>
                <label for="category">Catégorie :</label>
                <select id="category" name="category">
                    <?php foreach ($Category as $cate) :?>
                    	<option value="<?= $cate['Id']?> "><?= $cate['Name'] ?></option>



                	<?php endforeach ?>

                </select>
                <button><a href="add_category.php"> rajouter category</a></button>
                <button><a href="add_authors.php"> rajouter auteurs</a></button>
            </li>
            <li>
                <button class="button button-primary" type="submit">Enregistrer</button>
                <a class="button button-cancel" href="index.php">Annuler</a>
            </li>
        </ul>
    </fieldset>
</form>