<form class="generic-form" action="edit_post.php" method="post">
    <fieldset>
        <legend><i class="fa fa-sticky-note-o"></i> Nouvel article</legend>
        <ul>
        <input type="hidden" name="postId" value=<?=$_GET['id']?>>
            <li>
                <label for="title">Titre :</label>
                <input type="text" id="title" name="title" value="<?=$post['Title']?>">
            </li>
            <li>
                <label class="textarea" for="contents">Article :</label>
                <textarea id="contents" name="contents" rows="15" ><?=$post['Contents']?></textarea>
            </li>
            <li>
                <button class="button button-primary" type="submit">Enregistrer</button>
                <a class="button button-cancel" href="index.php">Annuler</a>
            </li>
        </ul>
    </fieldset>
</form>