
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Encore un Blog ?! #nonMaisAllo</title>

    <!-- Feuilles de style externes -->
    <link rel="stylesheet" href="css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans">

    <!-- Feuilles de style de l'application -->
    <link rel="stylesheet" href="css/blog-main.css">
    <link rel="stylesheet" href="css/blog-theme.css">
    <link rel="stylesheet" href="css/ui-button.css">
    <link rel="stylesheet" href="css/ui-form.css">
</head>
<body>
    <!-- En-tête commune de l'application -->
    <header class="blog-header">
        <h1><a href="blog_home.php"><i class="fa fa-microphone"></i>    <p> Pussy Ass Nword</p></a></h1>
        <nav>
            <?php if(array_key_exists('pseudo', $_SESSION)== false) : ?>
                <a href="login.php">login man</a>
            <?php endif ?>
            <?php if(array_key_exists('pseudo', $_SESSION)) :?>
               
                    <a href="logout.php">logout man</a>
            <?php endif ?>
            <?php if(array_key_exists('mail', $_SESSION)==false): ?>

                <a href="register.php">register</a>
            <?php endif ?>
            <?php if(array_key_exists('role', $_SESSION) == true && $_SESSION['role']== 'admin') :?>
                <a href="admin.php"><i class="fa fa-cogs"></i> Administration</a>
            <?php endif ?>
        </nav>
    </header>

    <main>
        <!-- Chargement du template PHTML spécifié par le programme PHP -->
        <?php include $template.'.phtml' ?>
    </main>

    <!-- Pied de page commun de l'application -->
    <footer class="blog-footer">
        <small>Le blog des élèves de la 3W Academy</small>
    </footer>
</body>
</html>
