<form action="register.php" method="POST">
	<ul>
		<li><label for="firstName">nom</label></li>
		<li><input id = "firstName" type="text" name="firstName"></li>
		<li><label for="lastName"> prenom</label></li>
		<li><input id = "lastName" type="text" name="lastName"></li>
		<li><label for="mail">mail</label>
		<li><input id = "mail" type="text" name="mail"></li>
		<li><label for="pseudo">pseudo</label>
		<li><input id = "pseudo" type="text" name="pseudo"></li>
		<li><label for="password">mot de passe</label>
		<li><input id = "password" type="text" name="password"></li>
		<li><button>s'inscrire</button>
	</ul>



	
	



</form>