<section id="editTable">
	<button type="button" id="divProduit">ajouter une div produit</button>
	<button type="button" id="divText">ajouter un texte</button>
	<button type="button" id="divImage">ajoutez une image</button>
	<button type="button" id="divTitre">ajouter un titre</button>
	<button type="button" id="apercus">apercus</button>

</section>





<section id="showForm">
	

</section>



<section id="showElement" width="800px" height="900px">
	<?php foreach ($prod as $produit) : ?>
		<div style="top:<?= $produit['PositionY']?>;left:<?= $produit['PositionX']?> ;position:absolute" id= <?=$produit['Id'] ?> class="move" width="200px" height="100px" >
			<img src="../membres/photoProduct/<?=$produit['ProductPhoto']?>">
			<p>Description : <?=$produit['ProductDescription']?></p>
			<p> Prix :<?=$produit['ProductPrice']?></p>
			<p>Quantité en stock : <?=$produit['ProductQuantity']?></p>
			<button id="delete" data-id="<?=$produit['Id'] ?>">supprimer</button>


		</div>



	<?php endforeach ?>

	<?php foreach ($text as $Text) : ?>
		<div style="top:<?= $Text['PositionY']?>;left:<?= $Text['PositionX']?> ;position:absolute" id= <?=$Text['id'] ?> class="move" >
	
		<pre><?=$Text['Text']?></pre>


		</div>



	<?php endforeach ?>
	
</section>






<script src="<?= $wwwUrl ?>/js/classes/Element.class.js"></script>
<script src="<?= $wwwUrl ?>/js/classes/requeteSend.class.js"></script>

<script src="<?= $wwwUrl ?>/js/classes/MovingElement.class.js"></script>