</form>
 <div class="container">
      <h2 class="my-4 text-center">Intro to react course price 50$</h2>
      <form action="<?= $requestUrl ?>/charge?orderId=<?=$orderId?>" method="post" id="payment-form">
        <div class="form-row">
          <input type="text" class="form-control mb-3 StripeElement StripeElemen--empty" placeHolder="Prénom" name="first_name">

          <input type="text" class="form-control mb-3 StripeElement StripeElemen--empty" placeHolder="Nom" name="last_name">

          <input type="email" class="form-control mb-3 StripeElement StripeElemen--empty" placeHolder="Email" name="email">

          <div id="card-element" class="form-control ">
            <!-- A Stripe Element will be inserted here. -->
          </div>

          <!-- Used to display form errors. -->
          <div id="card-errors" role="alert"></div>
        </div>

        <button>Submit Payment</button>
      </form>
    </div>
    <script src="https://js.stripe.com/v3/"></script>
    <script src="<?= $wwwUrl ?>/js/charge.js"></script>
