<!DOCTYPE html>
<html>
	<head>
		<title>api</title>
		<meta charset="utf-8">
	    <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>

	</head>
	<body>
		<header>
			
		</header>
		<main>
			<form method="movie.html" >
				<label for="research" name="search" >recherche</label>
				<input id="research" name="street" type="search"  >
				<button id="run" >valider</button>

			</form>
			<div id="target">
				
			</div>
			<div id="target2">
				
			</div>
		</main>
		
	</body>
	<script type="text/javascript" src="movie_api.js"></script>
	<script type="text/javascript" src="movie_event.js"></script>
	<script type="text/javascript" src="movie_main.js"></script>
</html>