<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Loterie 3Wacademy</title>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans">
    <link rel="stylesheet" href="lottery.css">
</head>
<body>
    <header>
        <h1>Traducteur Anglais - Français</h1>
    </header>
    <form action="traducteur.php" method="POST">
        <label for="mot">mot : </label>
        <input id="mot" type="text" name="mot">
      <input type="submit" value="Traduire">
        <label for="sens">mot : </label>
        <select name="langue">
            <option value=" toEnglish">français - anglais</option>
            <option value="toFrench">anglais- français</option>
         <button>traduire</button>
        </select>

    </form>
</body>
</html>