<fieldset>
	<legend> information produits </legend>
	<form action="<?= $requestUrl ?>/products/boutique" method="POST" enctype="multipart/form-data">
		<ul>
			<li>
				<label for="productName" name="productName">Nom produit </label>
				<input id="productName"  name="productName" type="text">
			</li>
			<li>
				<label for="productDescription" name="productDescription">description produit :  </label>
				<textarea id="productDescription"  name="productDescription" >
				</textarea>
			</li>
			<li>
				<label for="productCategory" name="productCategory">category :</label>
				<select name="productCategory" >
					<option values="Automobile">Automobile</option>
					<option values="Maison">Maison</option>
					<option values="Informatique">Informatique</option>
					<option values="Jeux-videos">Jeux-videos</option>
					<option values="Sport">Sport</option>
					<option values="Autre">Autre</option>
				</select>

				
			</li>
			<li>
				<label for="photoProduct" name="photoProduct">Ajoutez une photo du produit </label>
	<input name="photoProduct" type="file" />

	<input type="submit" value="Envoyer le fichier" />
			</li>
		</ul>
	</form>

</fieldset>