<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTPxtrjX\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTPxtrjX/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTPxtrjX.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTPxtrjX\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTPxtrjX\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TPxtrjX',
    'container.build_id' => '58846f71',
    'container.build_time' => 1559082409,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTPxtrjX');
