<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4FmrYeK\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4FmrYeK/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4FmrYeK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4FmrYeK\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container4FmrYeK\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '4FmrYeK',
    'container.build_id' => '799699db',
    'container.build_time' => 1559246567,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4FmrYeK');
