<!DOCTYPE html>
	<html lang="en">
		<head>
			<meta charset="UTF-8">
			<title>Document</title>
			<link rel="stylesheet" href="todo.css">
		</head>
		<body>
		<h1>Gestionaire de tâches :-) </h1>
		<form  action="remove.php" method="post" >
		<ul class="recap">
			<?php foreach($tasks as $index => $line ):?> 

			<li>
	  			<input type="checkbox" name="supprimer[]" id="titre" value="<?= $index ?>">
				<label for="titre" class="taille1 cool1" ><?= $line[0] ?>
				<?php if(date_create($line[2]) < $now): ?>
                	<strong>- en retard</strong>
                <?php endif ?>  
				</label>
                <p class="cool"><?= $line[1] ?></p></label>
			<li>
			<?php endforeach ?> 

		</ul>

			<button type="submit">supprimer</button>
		</form>

		<form action="todo.php" method="post">
			<fieldset>
			<legend>information sur la tache</legend>
			<label for="titre" class="taille1"> titre</label>
			<input type="text" name="title" id="titre" class="taille">
			<label for="tache" class="taille1">taches</label>
			<textarea name="tache" class="taille" id="#tache"></textarea>
				<label for="datedeFin" class="taille1">Date de fin :</label>
				<select name="jour" class="taille1">
					<option value="1">1</option>
					<option value="2">2</option>
					<option value="3" selected>3</option>
					<option value="4">4</option>
					<option value="5">5</option>
					<option value="6">6</option>
					<option value="7" selected>7</option>
					<option value="8">8</option>
					<option value="9">9</option>
					<option value="10">10</option>
					<option value="11" selected>11</option>
					<option value="12">12</option>
					<option value="13">13</option>
					<option value="14">14</option>
					<option value="15" selected>15</option>
					<option value="16">16</option>
					<option value="17">17</option>
					<option value="18">18</option>
					<option value="19" selected>19</option>
					<option value="20">20</option>
					<option value="21">21</option>
					<option value="22">22</option>
					<option value="23" selected>23</option>
					<option value="24">24</option>
					<option value="25">25</option>
					<option value="26">26</option>
					<option value="27" selected>27</option>
					<option value="28">28</option>
					<option value="29">29</option>
					<option value="30">30</option>
					<option value="31" selected>31</option>
			





					</select >
						<select name="mois" class="taille1">
						<option value="janvier">janvier</option>
						<option value="fevrier">fevrier</option>
						<option value="mars" selected>mars</option>
						<option value="avril">avril</option>
						<option value="mai">mai</option>
						<option value="juin">juin</option>
						<option value="juillet" selected>juillet</option>
						<option value="aout">aout</option>
						<option value="septembre">septembre</option>
						<option value="octobre">octobre</option>
						<option value="novembre" selected>novembre</option>
						<option value="decembre">decembre</option>
					</select>

					<select name="annee" class="taille1">
						<option value="2018">2018</option>
						<option value="2019">2019</option>
						<option value="2020" selected>2020</option>
						<option value="2021">2021</option>
						<option value="2022">2022</option>
					</select>

					<label for="priority" class="taille1">priorité</label><label for="basse"><input type="radio" name="priority" value="basse">basse</label>
					<label for="normale"><input type="radio" name="priority" value="normale">normale</label>
				<label for="haute"><input type="radio" name="priority" value="haute" checked>haute</label>
				<button type="submit">ajouter</button>


			</fieldset>
		</form>


		</body>


	</html>