<form action="register.php" method="POST">
	<ul>
		<li>
	<label for="firstName" name="firstName"> nom : </label>
	<input id="firstName" type="text" name="firstName" />
	</li>
	<li>
	<label for="lastName" name="lastName"> prenom : </label>
	<input id="lastName" type="text" name="lastName" />
	</li>
	<li>
	<label for="age" name="age"> age : </label>
	<input id="age" type="text" name="age" />
	</li>
	<li>
	<label for="email" name="email"> email : </label>
	<input id="email" type="text" name="email" />
	</li>
	<li>
	<label for="password" name="password"> mot de passe : </label>
	<input id="password" type="password" name="password" />
	</li>
	<button type="submit">enregistrer</button>
	</form>

</form>