<!-- Message de notification -->

<!-- Code HTML à écrire -->

<img src="<?=$wwwUrl?>/images/meals/no-photo.png?>/"/>
<div class="map_image">
<?php include "application/www/images/svg/france.php"; ?>
</div>
<div class="map_list">
	<ul>
		<li><a href="#" id="list-A"></a>a</li>
		<li><a href="#" id="list-B"></a>b</li>
		<li><a href="#" id="list-C"></a>c</li>
		<li><a href="#" id="list-D"></a>d</li>
		<li><a href="#" id="list-E"></a>e</li>
		<li><a href="#" id="list-F"></a>f</li>
		<li><a href="#" id="list-G"></a>g</li>
		<li><a href="#" id="list-H"></a>h</li>
		<li><a href="#" id="list-I"></a>i</li>
		<li><a href="#" id="list-J"></a>j</li>
		<li><a href="#" id="list-K"></a>k</li>
		<li><a href="#" id="list-L"></a>l</li>
		<li><a href="#" id="list-M"></a>m</li>
	</ul>
</div>
<!-- Liste des aliments -->
