<!-- Message de notification -->

<!-- Code HTML à écrire -->

<img src="<?=$wwwUrl?>/images/meals/no-photo.png?>/"/>
<div id="map">
<div id="map_image" class="map_image">
<?php include "application/www/images/svg/france.php"; ?>
</div>
<div class="map_list">
	<ul>
		<li><a href="#" id="list-GES">Grand Est</a></li>
		<li><a href="#" id="list-NAQ">Nouvelle-Aquitaine</a></li>
		<li><a href="#" id="list-ARA">Auvergne-Rhône-Alpes</a></li>
		<li><a href="#" id="list-BFC">Bourgogne-region-Franche-Comté</a></li>
		<li><a href="#" id="list-BRE">Bretagn</a></li>
		<li><a href="#" id="list-CVL">Centre-Val de Loire</a></li>
		<li><a href="#" id="list-COR">Corse</a></li>
		<li><a href="#" id="list-IDF">Île-de-France</a></li>
		<li><a href="#" id="list-OCC">Occitanie</a></li>
		<li><a href="#" id="list-HDF">Hauts-de-region-France</a></li>
		<li><a href="#" id="list-NOR">Normandie</a></li>
		<li><a href="#" id="list-PDL">Pays de la Loire</a></li>
		<li><a href="#" id="list-PAC">Provence-Alpes-Côte d'Azur</a></li>
	</ul>
</div>
</div>
<!-- Liste des aliments -->



<script src="<?=$wwwUrl?>/js/classes/Map.class.js"></script>